// NL lang variables
// update voor V2.1.2 door P.J. Sitter
// 26-10-2007

tinyMCE.addToLang('',{
theme_style_select : '-- Stijlen --',
theme_code_desc : 'HTML-tekstbron bewerken',
theme_code_title : 'HTML Code Editor',
theme_code_wordwrap : 'Tekstterugloop',
theme_sub_desc : 'Onderschrift',
theme_sup_desc : 'Bovenschrift',
theme_hr_desc : 'Horizontale lijn invoegen',
theme_removeformat_desc : 'Verwijder tekstopmaak',
theme_custom1_desc : 'Typ hier een omschrijving',
insert_image_border : 'Rand',
insert_image_dimensions : 'Afmetingen',
insert_image_vspace : 'Verticale marge',
insert_image_hspace : 'Horizontale marge',
insert_image_align : 'Uitlijning',
insert_image_align_default : '-- Geen --',
insert_image_align_baseline : 'Basisregel',
insert_image_align_top : 'Top',
insert_image_align_middle : 'Midden',
insert_image_align_bottom : 'Onder',
insert_image_align_texttop : 'Bovenkant tekst',
insert_image_align_absmiddle : 'Absoluut Midden',
insert_image_align_absbottom : 'Absoluut Onder',
insert_image_align_left : 'Links',
insert_image_align_right : 'Rechts',
theme_font_size : '-- Lettergrootte --',
theme_fontdefault : '-- Lettertype --',
theme_block : '-- Formaat --',
theme_paragraph : 'Paragraaf',
theme_div : 'Blok',
theme_address : 'Adres',
theme_pre : 'Opgemaakt',
theme_h1 : 'Kop 1',
theme_h2 : 'Kop 2',
theme_h3 : 'Kop 3',
theme_h4 : 'Kop 4',
theme_h5 : 'Kop 5',
theme_h6 : 'Kop 6',
theme_blockquote : 'Blockquote',
theme_code : 'Code',
theme_samp : 'Code voorbeeld',
theme_dt : 'Definitie term [dt] ',
theme_dd : 'Definitie omschrijving [dd]',
theme_colorpicker_title : 'Kies een kleur',
theme_colorpicker_apply : 'Toepassen',
theme_forecolor_desc : 'Kies tekstkleur',
theme_backcolor_desc : 'Kies achtergrondkleur',
theme_charmap_title : 'Kies speciale tekens',
theme_charmap_desc : 'Speciale tekens invoegen',
theme_visualaid_desc : 'Aan/uit aanduiding/onzichtbare elementen',
insert_anchor_title : 'Anker invoegen/aanpassen',
insert_anchor_name : 'Ankernaam',
theme_anchor_desc : 'Anker invoegen/aanpassen',
theme_insert_link_titlefield : 'Titel',
theme_clipboard_msg : 'Kopieer/Knip/Plak-opties niet beschikbaar in Mozilla/Firefox.\nWil je meer informatie hierover?',
theme_path : 'Pad',
cut_desc : 'Knip',
copy_desc : 'Kopieer',
paste_desc : 'Plak',
link_list : 'Hyperlink-lijst',
image_list : 'Afbeeldingenlijst',
browse : 'Bladeren',
image_props_desc : 'Eigenschappen afbeelding',
newdocument_desc : 'Nieuw document',
class_name : 'Stijl',
newdocument : 'Weet je zeker dat je de hele inhoud wilt wissen?',
about_title : 'Over TinyMCE',
about : 'Over',
license : 'Licentie',
plugins : 'Plugins',
plugin : 'Plugin',
author : 'Auteur',
version : 'Versie',
loaded_plugins : 'Ingeschakelde plugins',
help : 'Help',
not_set : '-- geen --',
close : 'Sluiten',
toolbar_focus : 'Ga naar Knoppenbalk - Alt+Q, Ga naar Editor - Alt-Z, Ga naar pad - Alt-X',
invalid_data : 'FOUT: Ongeldige waarden ingegeven; ze zijn rood aangegeven.',
more_colors : 'Meer kleuren',
color_picker_tab : 'Kleurenkiezer',
color_picker : 'Kleurenkiezer',
web_colors_tab : 'Palet',
web_colors : 'Kleurenpalet',
named_colors_tab : 'Namen en Kleuren',
named_colors : 'Kleuren en Namen',
color : 'Kleur:',
color_name : 'Naam:',
is_email : 'Het ingetypte adres lijkt een e-mailadres; moet dit programma de benodigde prefix:  mailto: toevoegen?',
is_external : 'Het ingetypte adres lijkt een externe link; moet dit programma de benodigde prefix: http:// toevoegen?'
});
